Re-sign request on retry
hashicorp/go-retryablehttp pull request #216
Opened 2024-03-08 15:43 UTC by mgwoj

In our case we need to re-sign request before initiating retry operation. To achieve that we have added a new handler `PrepareRetry` which can be used for this purpose, however the signature and the name is as generic as possible.

2024-03-08 15:43 UTC, hashicorp-cla commented
[![CLA assistant check](https://cla.hashicorp.com/pull/badge/not_signed)](https://cla.hashicorp.com/hashicorp/go-retryablehttp?pullRequest=216)


Thank you for your submission! We require that all contributors sign our Contributor License Agreement ("CLA") before we can accept the contribution. [Read and sign the agreement](https://cla.hashicorp.com/hashicorp/go-retryablehttp?pullRequest=216)

[Learn more about why HashiCorp requires a CLA and what the CLA includes](https://www.hashicorp.com/cla)

<sub>Have you signed the CLA already but the status is still pending? [Recheck it](https://cla.hashicorp.com/check/hashicorp/go-retryablehttp?pullRequest=216).</sub>

2024-04-23 06:21 UTC, manicminer requested changes
Thank you @mgwoj for this PR! This seems like a reasonable addition and I like the implementation. My only suggestion would be to accommodate a default `nil` value for `Client.PrepareRetry` - this would offer maximum compatibility for consumers who might be constructing their own `Client`.

2024-04-23 06:21 UTC, manicminer commented on client.go
> +		PrepareRetry: DefaultPrepareRetry,
Since this default function does nothing, can we leave the default as `nil` here?

2024-04-23 06:21 UTC, manicminer commented on client.go
> +
Not needed if we accommodate a nil value for `client.PrepareRetry`

2024-04-23 06:21 UTC, manicminer commented on client.go
> +		}
Per the above, can we conditionally attempt this if the function is non-nil?

```suggestion
		if c.PrepareRetry != nil {
			if err := c.PrepareRetry(req.Request); err != nil {
				prepareErr = err
				break
			}
		}
```

2024-04-26 07:07 UTC, mgwoj commented
Thank you for reviewing and accepting the proposed solution for prepare retry. I have applied your suggestions.

2024-05-07 19:21 UTC, manicminer approved these changes
Thanks @mgwoj, this LGTM! 👍

2024-05-08 19:58 UTC, manicminer approved these changes

2024-05-09 15:04 UTC, merged